### ISSUE TITLE
ライセンス文章が無い

### ISSUE THREAD

**Issue by IgaguriMK** [woopsdez/ComputerCraft#1]
ライセンス文章が無いので、GitHubのリポジトリを見ただけでは使用条件が分かりません。
何かしらの使用条件を記載したライセンス文章を付属させてください。

**Comment by woopsdez** [comment]
MIT ライセンスを付与し、readmeに追記。あとライセンス文も追加しました。

**Comment by IgaguriMK** [comment]
License.txtの3行目の「Copyright (c) [year] [fullname]」の所に作成年と著作権者の表示が抜けております。

**Comment by woopsdez** [comment]
おっと！ありがとうございます。

**Comment by IgaguriMK** [comment]
ありがとうございました。
